import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { MistralService } from '../MistralService';
import { ExaSearchResult } from '../../../types';

// Mock fetch globally
const mockFetch = vi.fn();
global.fetch = mockFetch;

describe('MistralService', () => {
  let service: MistralService;
  const mockApiKey = 'test-mistral-key';

  beforeEach(() => {
    service = new MistralService(mockApiKey);
    vi.clearAllMocks();
  });

  afterEach(() => {
    vi.resetAllMocks();
  });

  describe('constructor', () => {
    it('should create service with provided API key', () => {
      const testService = new MistralService('custom-key');
      expect(testService).toBeInstanceOf(MistralService);
    });

    it('should throw error when no API key is provided', () => {
      // Mock config to return empty API key
      vi.doMock('../../config', () => ({
        config: {
          apis: {
            mistralApiKey: '',
          },
        },
      }));

      expect(() => new MistralService()).toThrow('Mistral AI API key is required');
    });
  });

  describe('generateSummary', () => {
    const mockMistralResponse = {
      id: 'test-id',
      object: 'chat.completion',
      created: 1234567890,
      model: 'mistral-small-latest',
      choices: [
        {
          index: 0,
          message: {
            role: 'assistant',
            content: 'This is a test summary of the provided content.',
          },
          finish_reason: 'stop',
        },
      ],
      usage: {
        prompt_tokens: 50,
        completion_tokens: 20,
        total_tokens: 70,
      },
    };

    it('should generate summary successfully', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: async () => mockMistralResponse,
      });

      const summary = await service.generateSummary('This is test content to summarize.');

      expect(mockFetch).toHaveBeenCalledWith('https://api.mistral.ai/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${mockApiKey}`,
        },
        body: JSON.stringify({
          model: 'mistral-small-latest',
          messages: [
            {
              role: 'system',
              content: 'You are a helpful assistant that creates concise, informative summaries of web content. Focus on the key points and main ideas. Keep summaries under 150 words and make them easy to understand.',
            },
            {
              role: 'user',
              content: 'Please summarize the following content:\n\nThis is test content to summarize.',
            },
          ],
          max_tokens: 200,
          temperature: 0.3,
          top_p: 0.9,
          stream: false,
        }),
      });

      expect(summary).toBe('This is a test summary of the provided content.');
    });

    it('should throw error for empty content', async () => {
      await expect(service.generateSummary('')).rejects.toThrow('Content cannot be empty');
      await expect(service.generateSummary('   ')).rejects.toThrow('Content cannot be empty');
    });

    it('should handle 401 Unauthorized error', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: false,
        status: 401,
        text: async () => 'Unauthorized',
      });

      await expect(service.generateSummary('test content')).rejects.toThrow('Invalid API key for Mistral AI');
    });

    it('should handle 429 Rate Limit error', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: false,
        status: 429,
        text: async () => 'Rate limit exceeded',
      });

      await expect(service.generateSummary('test content')).rejects.toThrow('Rate limit exceeded for Mistral AI. Please try again later.');
    });

    it('should handle 500 Server Error', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: false,
        status: 500,
        text: async () => 'Internal server error',
      });

      await expect(service.generateSummary('test content')).rejects.toThrow('Mistral AI service is temporarily unavailable');
    });

    it('should handle empty choices in response', async () => {
      const emptyResponse = {
        ...mockMistralResponse,
        choices: [],
      };

      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: async () => emptyResponse,
      });

      await expect(service.generateSummary('test content')).rejects.toThrow('No response generated by Mistral AI');
    });

    it('should truncate long content', async () => {
      const longContent = 'a'.repeat(3000);
      
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: async () => mockMistralResponse,
      });

      await service.generateSummary(longContent);

      const callBody = JSON.parse(mockFetch.mock.calls[0][1].body);
      const userMessage = callBody.messages[1].content;
      
      // Should be truncated to around 2000 characters plus the prompt prefix
      expect(userMessage.length).toBeLessThan(2100);
      expect(userMessage).toContain('Please summarize the following content:');
    });
  });

  describe('enhanceResult', () => {
    const mockResult: ExaSearchResult = {
      title: 'Test Article',
      url: 'https://example.com/article',
      text: 'This is the content of the test article.',
      score: 0.9,
    };

    it('should enhance result with AI summary', async () => {
      const mockResponse = {
        choices: [
          {
            message: {
              content: 'Enhanced summary of the article.',
            },
          },
        ],
      };

      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: async () => mockResponse,
      });

      const enhanced = await service.enhanceResult(mockResult);
      expect(enhanced).toBe('Enhanced summary of the article.');
    });

    it('should return fallback for result with no text', async () => {
      const resultWithoutText: ExaSearchResult = {
        ...mockResult,
        text: '',
      };

      const enhanced = await service.enhanceResult(resultWithoutText);
      expect(enhanced).toBe('Test Article');
    });

    it('should return fallback when AI enhancement fails', async () => {
      mockFetch.mockRejectedValueOnce(new Error('API Error'));

      // Mock console.warn to avoid test output
      const consoleSpy = vi.spyOn(console, 'warn').mockImplementation(() => {});

      const enhanced = await service.enhanceResult(mockResult);
      expect(enhanced).toBe('This is the content of the test article.');
      
      consoleSpy.mockRestore();
    });
  });

  describe('enhanceMultipleResults', () => {
    const mockResults: ExaSearchResult[] = [
      {
        title: 'Article 1',
        url: 'https://example.com/1',
        text: 'Content 1',
        score: 0.9,
      },
      {
        title: 'Article 2',
        url: 'https://example.com/2',
        text: 'Content 2',
        score: 0.8,
      },
    ];

    it('should enhance multiple results', async () => {
      const mockResponse = {
        choices: [
          {
            message: {
              content: 'Enhanced summary',
            },
          },
        ],
      };

      mockFetch
        .mockResolvedValueOnce({
          ok: true,
          json: async () => mockResponse,
        })
        .mockResolvedValueOnce({
          ok: true,
          json: async () => mockResponse,
        });

      const enhanced = await service.enhanceMultipleResults(mockResults);
      expect(enhanced).toHaveLength(2);
      expect(enhanced[0]).toBe('Enhanced summary');
      expect(enhanced[1]).toBe('Enhanced summary');
    });

    it('should handle partial failures gracefully', async () => {
      const mockResponse = {
        choices: [
          {
            message: {
              content: 'Enhanced summary',
            },
          },
        ],
      };

      // Mock console.warn to avoid test output
      const consoleSpy = vi.spyOn(console, 'warn').mockImplementation(() => {});

      mockFetch
        .mockResolvedValueOnce({
          ok: true,
          json: async () => mockResponse,
        })
        .mockRejectedValueOnce(new Error('API Error'));

      const enhanced = await service.enhanceMultipleResults(mockResults);
      expect(enhanced).toHaveLength(2);
      expect(enhanced[0]).toBe('Enhanced summary');
      expect(enhanced[1]).toBe('Content 2'); // Fallback for failed enhancement
      
      consoleSpy.mockRestore();
    });
  });

  describe('isServiceAvailable', () => {
    it('should return true when service is available', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: async () => ({
          choices: [
            {
              message: {
                content: 'Test response',
              },
            },
          ],
        }),
      });

      const isAvailable = await service.isServiceAvailable();
      expect(isAvailable).toBe(true);
    });

    it('should return false when service is unavailable', async () => {
      mockFetch.mockRejectedValueOnce(new Error('Service unavailable'));

      const isAvailable = await service.isServiceAvailable();
      expect(isAvailable).toBe(false);
    });
  });

  describe('content truncation', () => {
    it('should truncate at sentence boundary when possible', () => {
      const longText = 'First sentence. Second sentence. Third sentence. ' + 'a'.repeat(2000);
      
      // Access private method through any cast for testing
      const truncated = (service as any).truncateContent(longText, 50);
      
      // The logic should find the last sentence boundary within 70% of maxLength
      // Since "First sentence. Second sentence." is 33 chars and 70% of 50 is 35,
      // it should include "Third sentence." as well since it's within the limit
      expect(truncated).toBe('First sentence. Second sentence. Third sentence.');
    });

    it('should truncate at word boundary when no sentence boundary', () => {
      const longText = 'word1 word2 word3 word4 ' + 'a'.repeat(2000);
      
      const truncated = (service as any).truncateContent(longText, 30);
      
      expect(truncated).toContain('...');
      expect(truncated.length).toBeLessThan(35);
    });

    it('should return original text if under limit', () => {
      const shortText = 'Short text';
      
      const truncated = (service as any).truncateContent(shortText, 100);
      
      expect(truncated).toBe(shortText);
    });
  });
});