import { ExaSearchResult } from '../../types';
import { config } from '../config';

export interface MistralMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

export interface MistralChatRequest {
  model: string;
  messages: MistralMessage[];
  max_tokens?: number;
  temperature?: number;
  top_p?: number;
  stream?: boolean;
}

export interface MistralChatResponse {
  id: string;
  object: string;
  created: number;
  model: string;
  choices: Array<{
    index: number;
    message: {
      role: string;
      content: string;
    };
    finish_reason: string;
  }>;
  usage: {
    prompt_tokens: number;
    completion_tokens: number;
    total_tokens: number;
  };
}

export class MistralService {
  private readonly apiKey: string;
  private readonly baseUrl = 'https://api.mistral.ai/v1';
  private readonly model = 'mistral-small-latest';

  constructor(apiKey?: string) {
    this.apiKey = apiKey || config.apis.mistralApiKey;
    
    if (!this.apiKey) {
      throw new Error('Mistral AI API key is required');
    }
  }

  async enhanceResult(result: ExaSearchResult): Promise<string> {
    if (!result.text || result.text.trim().length === 0) {
      return result.title || 'No content available for summarization';
    }

    try {
      const summary = await this.generateSummary(result.text);
      return summary;
    } catch (error) {
      // Fallback to original content if AI enhancement fails
      console.warn('Failed to enhance result with Mistral AI:', error);
      return this.createFallbackSummary(result);
    }
  }

  async generateSummary(content: string): Promise<string> {
    if (!content.trim()) {
      throw new Error('Content cannot be empty');
    }

    // Truncate content if it's too long (Mistral has token limits)
    const truncatedContent = this.truncateContent(content, 2000);

    const messages: MistralMessage[] = [
      {
        role: 'system',
        content: 'You are a helpful assistant that creates concise, informative summaries of web content. Focus on the key points and main ideas. Keep summaries under 150 words and make them easy to understand.',
      },
      {
        role: 'user',
        content: `Please summarize the following content:\n\n${truncatedContent}`,
      },
    ];

    const requestBody: MistralChatRequest = {
      model: this.model,
      messages,
      max_tokens: 200,
      temperature: 0.3,
      top_p: 0.9,
      stream: false,
    };

    try {
      const response = await fetch(`${this.baseUrl}/chat/completions`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${this.apiKey}`,
        },
        body: JSON.stringify(requestBody),
      });

      if (!response.ok) {
        await this.handleAPIError(response);
      }

      const data: MistralChatResponse = await response.json();
      
      if (!data.choices || data.choices.length === 0) {
        throw new Error('No response generated by Mistral AI');
      }

      return data.choices[0].message.content.trim();
    } catch (error) {
      if (error instanceof Error) {
        throw error;
      }
      throw new Error('Failed to generate summary with Mistral AI');
    }
  }

  async enhanceMultipleResults(results: ExaSearchResult[]): Promise<string[]> {
    const enhancementPromises = results.map(result => 
      this.enhanceResult(result).catch(error => {
        console.warn(`Failed to enhance result for ${result.url}:`, error);
        return this.createFallbackSummary(result);
      })
    );

    return Promise.all(enhancementPromises);
  }

  private async handleAPIError(response: Response): Promise<never> {
    const errorText = await response.text();
    
    switch (response.status) {
      case 400:
        throw new Error(`Invalid request to Mistral AI: ${errorText}`);
      case 401:
        throw new Error('Invalid API key for Mistral AI');
      case 429:
        throw new Error('Rate limit exceeded for Mistral AI. Please try again later.');
      case 500:
        throw new Error('Mistral AI service is temporarily unavailable');
      default:
        throw new Error(`Mistral AI API error (${response.status}): ${errorText}`);
    }
  }

  private truncateContent(content: string, maxLength: number): string {
    if (content.length <= maxLength) {
      return content;
    }

    // Try to truncate at a sentence boundary
    const truncated = content.substring(0, maxLength);
    const lastSentenceEnd = Math.max(
      truncated.lastIndexOf('.'),
      truncated.lastIndexOf('!'),
      truncated.lastIndexOf('?')
    );

    if (lastSentenceEnd > maxLength * 0.7) {
      return truncated.substring(0, lastSentenceEnd + 1);
    }

    // If no good sentence boundary, truncate at word boundary
    const lastSpace = truncated.lastIndexOf(' ');
    if (lastSpace > maxLength * 0.8) {
      return truncated.substring(0, lastSpace) + '...';
    }

    return truncated + '...';
  }

  private createFallbackSummary(result: ExaSearchResult): string {
    // Create a simple fallback summary from the title and beginning of text
    const title = result.title || 'Untitled';
    const text = result.text || '';
    
    if (text.length <= 150) {
      return text || title;
    }

    const truncated = this.truncateContent(text, 150);
    return truncated;
  }

  // Health check method for service availability
  async isServiceAvailable(): Promise<boolean> {
    try {
      // Perform a minimal request to check service availability
      await this.generateSummary('This is a test content for health check.');
      return true;
    } catch (error) {
      return false;
    }
  }
}

// Export a factory function to create instances
export const createMistralService = (apiKey?: string) => new MistralService(apiKey);

// Export a default instance only if API key is available
export const mistralService = config.apis.mistralApiKey ? new MistralService() : null;